#!/usr/bin/env python3
"""Heuristic Kummer/Matthews-type model for JOINT Artin densities of two bases.

density = sum_{m,n squarefree} mu(m)mu(n) / [Q(zeta_L, a^{1/m}, b^{1/n}) : Q],  L=lcm(m,n)
Generic degree = phi(L)*m*n; it DROPS by the number of elements of the group
V = <d_a (if 2|m), d_b (if 2|n)>  in Q*/squares whose quadratic field sits
inside Q(zeta_L) (i.e. whose conductor divides L).  eps = |V ∩ cyclo(L)|.

Primes in S (the ramified/relevant set) are summed exactly; the rest go into an
Euler product.  Verified against known single-base Hooley densities.
"""
import math, itertools, json
from sympy import primerange, factorint

PMAX = 3_000_000

def sqf(n):
    s = 1
    for q, e in factorint(n).items():
        if e % 2: s *= q
    return s

def conductor(d):
    """conductor of Q(sqrt(d)) for squarefree d>1"""
    return d if d % 4 == 1 else 4*d

_PR=None
def _primes():
    global _PR
    if _PR is None: _PR=list(primerange(2,PMAX))
    return _PR

def euler_outside(S):
    """prod_{q not in S} (1 - (2q-1)/((q-1) q^2))  [pair version]"""
    tot = 0.0
    S=set(S)
    for q in _primes():
        if q in S: continue
        tot += math.log(1 - (2*q-1)/((q-1)*q*q))
    return math.exp(tot)

def euler_outside_single(S):
    """prod_{q not in S} (1 - 1/(q(q-1)))  [single-base version]"""
    tot = 0.0
    S=set(S)
    for q in _primes():
        if q in S: continue
        tot += math.log(1 - 1/(q*(q-1)))
    return math.exp(tot)

def phi_int(n):
    r = 1
    for q, e in factorint(n).items(): r *= (q-1)*q**(e-1)
    return r

def subsets(L):
    for r in range(len(L)+1):
        for c in itertools.combinations(L, r): yield c

def single_density(d, Sextra=()):
    """Hooley density for base with squarefree part d, via S-sum + Euler tail."""
    S = sorted(set([2]) | set(factorint(d)) | set(Sextra))
    out = euler_outside_single(S)
    tot = 0.0
    for sub in subsets(S):
        m = 1
        for q in sub: m *= q
        mu = (-1)**len(sub)
        eps = 2 if (m % 2 == 0 and conductor(d) % 1 == 0 and m % 2 == 0
                    and (m % conductor(d) == 0 if conductor(d) % 2 else False)) else 1
        # eps=2 iff 2|m and conductor(d) | m
        eps = 2 if (m % 2 == 0 and m % conductor(d) == 0) else 1
        tot += mu * eps / (phi_int(m) * m)
    return tot * out

def joint_density(da, db):
    dc = sqf(da*db)
    S = sorted(set([2]) | set(factorint(da)) | set(factorint(db)))
    out = euler_outside(S)
    conds = {da: conductor(da), db: conductor(db), dc: conductor(dc)}
    tot = 0.0
    for subm in subsets(S):
        m = 1
        for q in subm: m *= q
        for subn in subsets(S):
            n = 1
            for q in subn: n *= q
            L = m*n // math.gcd(m, n)
            mu = (-1)**(len(subm)+len(subn))
            # V is the subgroup of Q*/(Q*)^2 generated by the quadratic classes
            # forced into the field: <d_a (if 2|m), d_b (if 2|n)>.  Because it has
            # at most two generators, |V| <= 4.
            #
            # eps is the ORDER OF THE SUBGROUP of V realised inside Q(zeta_L),
            # i.e. eps = |V ∩ cyclo(L)| -- NOT 2^(number of such classes).  The
            # latter overcounts: with d_a, d_b and their product d_a*d_b ~ sqf(ab)
            # all of conductor dividing L it returns 2^3 = 8 > |V|, which is
            # impossible for a subgroup of a group of order 4.  Enumerate the
            # subgroup explicitly and count the classes actually realised.
            gens = []
            if m % 2 == 0: gens.append(da)
            if n % 2 == 0: gens.append(db)
            # close <gens> under multiplication mod squares (squarefree kernel)
            V = {1}
            for g in gens:
                V |= {sqf(v * g) for v in V}
            eps = sum(1 for v in V if L % conductor(v) == 0)
            tot += mu * eps / (phi_int(L) * m * n)
    return tot * out

if __name__ == "__main__":
    # Measured marginals recovered from results/crossbase_fine_1e9.json at x=1e9.
    # (Earlier versions of this block carried stale values for d=2, 13, 17, 29;
    #  they were display-only and never fed the joint-density comparison, but they
    #  disagreed with the shipped data by up to 7e-5, so they are corrected here.)
    print("VALIDATION — single-base densities (measured from crossbase_fine_1e9.json)")
    for d, meas in ((2, 0.373957), (3, 0.373951), (5, 0.393642), (13, 0.376362),
                    (17, 0.375369), (29, 0.374439)):
        mod = single_density(d)
        print(f"  d={d:>3}  model={mod:.6f}   measured={meas:.6f}   |diff|={abs(mod-meas):.2e}")

def _find_data(name='crossbase_fine_1e9.json'):
    """Locate the contingency-table JSON whether run from code/ or the package root.

    Shipped layout puts the raw tables in ../results/, so a bare open(name) only
    worked if the file had been copied next to this script. Checks, in order:
    $CROSSBASE_DATA, cwd, ./results, ../results relative to this file.
    """
    import os
    env = os.environ.get('CROSSBASE_DATA')
    here = os.path.dirname(os.path.abspath(__file__))
    cands = ([env] if env else []) + [
        name,
        os.path.join('results', name),
        os.path.join(here, name),
        os.path.join(here, '..', 'results', name),
    ]
    for c in cands:
        if c and os.path.exists(c):
            return c
    raise FileNotFoundError(
        f"could not locate {name}; tried {cands}. "
        f"Set CROSSBASE_DATA=/path/to/{name} or run from the package root.")

def run_all():
    import json, math
    d = json.load(open(_find_data()))
    N = d['n_primes']; B = d['bases']
    rows = []
    for k, m in d['pairs'].items():
        a, b = map(int, k.split(','))
        n00, n01 = m[0]; n10, n11 = m[1]
        tot = n00+n01+n10+n11
        pa = (n10+n11)/tot; pb = (n01+n11)/tot; j = n11/tot
        da, db = sqf(a), sqf(b)
        mj = joint_density(da, db)
        ma, mb = single_density(da), single_density(db)
        # phi from densities
        def phi_of(pa, pb, j):
            return (j - pa*pb)/math.sqrt(pa*(1-pa)*pb*(1-pb))
        rows.append(dict(a=a, b=b, meas_joint=j, model_joint=mj,
                         meas_phi=phi_of(pa,pb,j), model_phi=phi_of(ma,mb,mj),
                         dep=(sqf(da*db) in [sqf(c) for c in B if c not in (a,b)])))
    return rows

if __name__ == "__main__" and True:
    rows = run_all()
    rows.sort(key=lambda r: -abs(r['meas_phi']))
    print(f"\n{'a':>3} {'b':>3} {'meas j':>9} {'model j':>9} {'rel.err':>8} "
          f"{'meas phi':>9} {'model phi':>9} {'dep':>4}")
    print('-'*66)
    errs = []
    for r in rows:
        e = (r['model_joint']-r['meas_joint'])/r['meas_joint']
        errs.append(abs(e))
        print(f"{r['a']:>3} {r['b']:>3} {r['meas_joint']:>9.6f} {r['model_joint']:>9.6f} "
              f"{100*e:>7.3f}% {r['meas_phi']:>+9.5f} {r['model_phi']:>+9.5f} "
              f"{'YES' if r['dep'] else '':>4}")
    print(f"\nmean |rel err| on joint density: {100*sum(errs)/len(errs):.3f}%")
    print(f"max  |rel err|: {100*max(errs):.3f}%")
    json.dump(rows, open('kummer_model_comparison.json','w'), indent=1)
